name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * */2'

permissions:
  contents: write
  pull-requests: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
    container:
      image: ghcr.io/jhnc-oss/yocto-image/yocto:42
      options: --user root
    name: "Build (${{ matrix.arch }})"
    steps:
      - uses: actions/checkout@main
      - name: Synchronize Repositories
        run: |
          PATH="${HOME}/.local/bin:${PATH}"
          repo init -u https://github.com/jhnc-oss/yocto-manifests.git -b main
          repo sync
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto

      - name: Install gh and jq
        run: |
          sudo dnf install -y dnf5-plugins jq
          sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo
          sudo dnf install -y gh --repo gh-cli
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto

      - name: Build
        run: |
          export YOCTO_TARGET_ARCH=${{ matrix.arch }}
          export BB_ENV_PASSTHROUGH_ADDITIONS=YOCTO_TARGET_ARCH
          export TEMPLATECONF=/opt/yocto/protos/meta-protos/conf/templates/default
          echo 'INHERIT += "cve-check"' >> /opt/yocto/protos/meta-protos/conf/templates/default/local.conf.sample
          source poky/oe-init-build-env
          bitbake openssl --runall=fetch
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto

      - name: Generate nvdcve label
        id: date
        run: echo "today=$(date -u +'%Y-%m-%d-%H-%MZ')" >> "$GITHUB_OUTPUT"

      - name: Upload CVE DB artifact
        uses: actions/upload-artifact@v6
        with:
          name: cvedb-${{ steps.date.outputs.today }}
          path: /opt/yocto/download/CVE_CHECK/nvdcve_2-2.db

      - name: Cleanup old artifacts (keep only 3)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts \
            --jq '.artifacts | sort_by(.created_at) | reverse')

          count=$(echo "$artifacts" | jq length)

          if [ "$count" -gt 3 ]; then
            echo "$artifacts" \
              | jq -r ".[$((3)):] | .[].id" \
              | while read id; do
                  echo "Deleting artifact ID: $id"
                  gh api \
                    --method DELETE \
                    -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2026-03-10" \
                    /repos/${{ github.repository }}/actions/artifacts/$id
                done
          else
            echo "No cleanup needed: only $count artifact(s) found."
          fi
